apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: forecastapp
  name: release
  description: forecastapp
  links:
    - url: http://localhost:8888
      title: launch app
      icon: dashboard
spec:
  lifecycle: production
  owner: guests
  type: service
