apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: forecastapp
  name: release
  description: forecastapp
spec:
  lifecycle: production
  owner: guests
  type: service
