apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: forecastapp
  name: forecastapp
spec:
  lifecycle: production
  owner: my-team
  type: service
