apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: forecastapp
    dynatrace.com/guardian-tags: 'service=forecastapp'
  name: release
  description: forecastapp
  dynatrace:
    queries:
      - id: Logs
        description: Fetch Logs
        query: >
          fetch logs, from: -24h
                | filter matchesValue(k8s.deployment.name, "forecastapp-*")
                | sort timestamp desc
                | fieldsAdd content=if(isNull(content), "N/A", else: content)
                | fieldsAdd source=if(isNull(log.source), "N/A", else: log.source)
                | fieldsAdd host=if(isNull(host.name), "N/A", else: host.name)
                | fieldsAdd environment = "lvo35023"
                | fieldsKeep timestamp, source, content, host, environment
  links:
    - url: http://localhost:8888
      title: launch app
      icon: dashboard
spec:
  lifecycle: production
  owner: guests
  type: service
